---
# Copyright (c) 2014 fStream. All Rights Reserved.

- name: Make sure python packages are installed
  apt: pkg={{ item }}
  with_items:
    - cython
    - libevent-dev
    - python
    - python3
    - python-dev

# Install dependancies
- apt: name=python-pip state=present

- name: Make sure virtualenv is installed
  pip: name=virtualenv
