---
# Copyright (c) 2014 fStream. All Rights Reserved.
#
# Description:
#   Global variables for all hosts in all playbooks

# External URLs 
external_submission_url: https://submissions.dcc.icgc.org
external_docs_url: http://docs.icgc.org

# Artifactory URLS
artifactory_url: http://seqwaremaven.oicr.on.ca/artifactory
artifactory_release_url: "{{ artifactory_url }}/dcc-release" 
artifactory_deps_url: "{{ artifactory_url }}/simple/dcc-dependencies" 

# Directories
staging_dir: "/tmp"
