---
# Copyright (c) 2015 fStream. All Rights Reserved.

# Configure
zeppelin_dir: /usr/local/zeppelin
zeppelin_log_dir: /var/log/zeppelin
zeppelin_server_port: '8090'
zeppelin_mem: '-Xmx2048m'

zeppelin_java_home: /usr/local/java/jdk
zeppelin_hadoop_conf_dir: /etc/hadoop/conf

# Spark
zeppelin_master: spark://localhost:7077
zeppelin_spark_executor_instances: '20'
zeppelin_spark_executor_cores: '1'
zeppelin_spark_executor_memory: '2g'

# User
zeppelin_user: zeppelin

# Build
zeppelin_git_url: 'https://github.com/apache/incubator-zeppelin.git'
zeppelin_src_dir: '/usr/src/zeppelin'
zeppelin_version: 'master'
zeppelin_comiple_flag: '-Pspark-1.3 -Phadoop-2.6 -DskipTests -P build-distr'
zeppelin_hadoop_version: '2.6.0-cdh5.4.3'

# Install
zeppelin_package_base_url: 'https://seqwaremaven.oicr.on.ca/artifactory/dcc-dependencies'
zeppelin_package_name: 'zeppelin-0.5.0-incubating-SNAPSHOT'
zeppelin_package_suffix: '.tar.gz'
zeppelin_spark_home: /usr/lib/spark
