# Copyright (c) 2014 fStream. All Rights Reserved.
#
# fStream - Vagrant settings file
#
# Description: 
#   The is the Vagrant setting file for provisioning the fStream stack using the 
#   VirtualBox provider within a single VM.

provider: virtualbox
boxes:

   # fStream
   - name: fstream
     groups:
        - influxdb
        - zookeeper
        - kafka
        - storm
        - fstream-persist
        - fstream-rates
        - fstream-compute
        - fstream-web
     virtualbox:
        memory: 4096
        cpus: 8
        forwarded_ports:
           - guest: 8081
             host: 8080
           - guest: 8080
             host: 8081
           - guest: 8083
             host: 9000             
