---
# Copyright (c) 2015 fStream. All Rights Reserved.
# 
# Project and contact information: https://bitbucket.org/fstream/fstream
# 
# Unauthorized copying of this file, via any medium is strictly prohibited.
# Proprietary and confidential.

###############################################################################
# Profile Activation
###############################################################################

# Profiles
spring.profiles.active:

###############################################################################
# Profile - common
###############################################################################

# Test     
test:
   workDir: /tmp/fstream-test      

# Kafka
kafka:
   brokerProperties:
      host.name: localhost      
      port: 6667
      broker.id: 0
      zookeeper.connect: ${zk.connect}
      log.dirs: ${test.workDir}/kafka
      log.retention.bytes: 2147483648 # 2 GB
