---
spark_version: "1.5.0"
spark_download_url: "http://www.apache.org/dyn/closer.lua/spark/spark-1.5.0/spark-{{ spark_version }}-bin-hadoop2.6.tgz"

spark_root: "/opt/spark"
spark_master_host: "{{ spark_master_host }}"
spark_master_port: 7077

# memory per executor, increase if see java out-of-memory exceptions in spark shell
spark_executor_memory: "{{ (ansible_memtotal_mb * 0.6) | round | int }}m"

# total memory for use by all apps
# make sure to leave at least 1gb for the system on slaves
# TODO set this value depending on total cluster memory
spark_worker_memory: 14g
