---
# Copyright (c) 2015 fStream. All Rights Reserved.
# 
# Project and contact information: https://bitbucket.org/fstream/fstream
# 
# Unauthorized copying of this file, via any medium is strictly prohibited.
# Proprietary and confidential.

###############################################################################
# Profile Activation
###############################################################################

# Available environment profiles:
# - development
# - production

# Profiles
spring.profiles.active: 

###############################################################################
# Profile - common
###############################################################################

# Kafka
kafka:
   consumerProperties:
      group.id: fstream-analyze

# Analyze
analyze:
   n: 20
   batchInterval: 5 # Seconds
   checkpointDir: /tmp/fstream-persist/checkpoint
   
   
# Spark
spark:
   properties:
#      spark.serializer: org.apache.spark.serializer.KryoSerializer
#      spark.kryo.registrator: io.fstream.analyze.util.CustomKryoRegistrator

---

###############################################################################
# Profile - "production"
###############################################################################

# Profile
spring.profiles: production

# Spark
spark:
   properties:
     
---

###############################################################################
# Profile - "development"
###############################################################################

# Profile
spring.profiles: development

# Spark
spark:
   # Need as many threads as (# of topics + 1) to service the streams. 
   # "local[*]" indicates physical cores on machine (8 typically)
   master: local[*] 