---
# Copyright (c) 2015 fStream. All Rights Reserved.

- name: Install NTP daemon
  become: yes
  apt: pkg=ntp state=present

- name: Ensure NTP daemon autostart
  become: yes
  service: name=ntp enabled=yes

- name: Setup NTP daemon config
  become: yes
  # Not read for prime time
  #template: src=etc/ntpd.conf.j2 dest=/etc/ntpd.conf
  debug: msg="*** Skipping"
  notify: Restart NTP daemon
