---
# Copyright (c) 2014 fStream. All Rights Reserved.

- name: Download Storm distribution
  get_url: "url={{ storm_archive_url }} dest={{ staging_dir }}/{{ storm_archive }} mode=0444"
  
# Ensure target dir exists
- name: Creating target dir
  file: "dest={{ target_dir }} state=directory"

# Install the Storm files to the specified location
- name: Extract Storm
  command: "tar xzf {{ staging_dir }}/{{  storm_archive }} -C {{ target_dir }} creates={{ target_dir }}/{{ storm_dir }}" 
  