---
# Copyright (c) 2015 fStream. All Rights Reserved.
# 
# Project and contact information: https://bitbucket.org/fstream/fstream
# 
# Unauthorized copying of this file, via any medium is strictly prohibited.
# Proprietary and confidential.

###############################################################################
# Profile Activation
###############################################################################

# Profiles
spring.profiles.active:

###############################################################################
# Profile - common
###############################################################################

# ZooKeeper
zk:
   connect: localhost:21812

# Kafka
kafka:
   producerProperties:
      metadata.broker.list: ${kafka.broker.list:localhost:6667}
      request.required.acks: 1
      serializer.class: kafka.serializer.StringEncoder
      partitioner.class: kafka.producer.DefaultPartitioner
   consumerProperties:
      zookeeper.connect: ${zk.connect}
      zookeeper.connection.timeout.ms: 1000000
      
# InfluxDB
influxdb:
   username: root
   password: root
   port: 8086
   host: localhost
   database: fstream-events
   url: http://${influxdb.host}:${influxdb.port}

# State     
state:

   # Registered instruments
   symbols:
     - RY
     - BMO
     - TD
     - BBM
     - HUF

   # Registered instruments
   fxSymbols:
     - EUR/USD
     - USD/JPY
     - GBP/USD
     - AUD/USD
     - USD/CHF
     - USD/CAD
     - AUD/NZD
     - NZD/USD

   # Common statements
   statements:

      - |
        CREATE CONTEXT 
           SegmentedBySymbol
        PARTITION BY 
           symbol 
        FROM
           Quote
      
   alerts:
         
      - id: 1
        name: Relative Tick Threshold
        description: Tick-to-tick percentage is greater than 1%
        statement: |
           CONTEXT SegmentedBySymbol
           SELECT
              ask / prior(1, ask) AS askPercentChange, symbol,dateTime
           FROM
              Quote
           WHERE
              ask / prior(1, ask) > 1.01

      - id: 2
        name: Flat Pricing
        description: Coded to fire many times. Final implementation would count < 1 every 60 secs.
        statement: |
           CONTEXT SegmentedBySymbol
           SELECT
               symbol, dateTime,
               COUNT(*) AS eventCnt 
           FROM
               Quote.win:time(60 sec)
           GROUP BY 
               symbol
           HAVING
               COUNT(*) < 1

      - id: 3
        name: Bursty Pricing
        description: A high amount of quote activity per second.
        statement: |
           CONTEXT SegmentedBySymbol
           SELECT
               symbol, 
               COUNT(*) AS eventCnt 
           FROM
               Quote.win:time(1 sec)
           GROUP BY 
               symbol
           HAVING
               COUNT(*) > 20

      - id: 4
        name: AUDNZD Cross Mispricing
        description: Identifies AUDNZD cross pair mispricing
        statement: |
           SELECT 
               adt,  bdt,  cdt,
               amid, bmid, cmid, 
               amid - (bmid * cmid) AS diff
           FROM 
               Quote(symbol in ['AUD/USD','AUD/NZD','NZD/USD']).win:time(1 millisecond)
           MATCH_RECOGNIZE (
               MEASURES 
                  last(A.mid)      AS amid, last(B.mid)      AS bmid, 
                  last(C.mid)      AS cmid, last(A.dateTime) AS adt, 
                  last(B.dateTime) AS bdt,  last(C.dateTime) AS cdt
               PATTERN 
                  ((A+ B+ C+) | (A+ C+ B+) | (B+ A+ C+) | (B+ C+ A+) | (C+ A+ B+) | (C+ B+ A+)) 
               DEFINE
                  A AS Quote.symbol = 'AUD/USD',
                  B AS Quote.symbol = 'AUD/NZD',
                  C AS Quote.symbol = 'NZD/USD'
           )
           WHERE
               amid - (bmid * cmid) > 0.00001

   metrics:

      - id: 1
        name: Events per Minute
        description: Calculates the number of events per minute across all instruments
        units: Events / min
        statement: |
           SELECT
               COUNT(*) AS count
           FROM
               Quote.win:time_batch(1 min)

      - id: 2
        name: Alerts per Minute
        description: Calculates the number of alerts per minute
        units: Alert / min
        statement: |
           SELECT
               COUNT(*) AS count
           FROM
               Alert.win:time_batch(1 min)
