---
# Copyright (c) 2015 fStream. All Rights Reserved.
# 
# Project and contact information: https://bitbucket.org/fstream/fstream
# 
# Unauthorized copying of this file, via any medium is strictly prohibited.
# Proprietary and confidential.

###############################################################################
# Profile Activation
###############################################################################

# Profiles
spring.profiles.active: development

###############################################################################
# Profile - common
###############################################################################

# ZooKeeper
zk:
   connect: localhost:21812

# Kafka
kafka:
   producerProperties:
      metadata.broker.list: ${kafka.broker.list:localhost:6667}
      request.required.acks: 1
      serializer.class: kafka.serializer.StringEncoder
      
# Storm
storm:
   properties:
      nimbus.host: ${storm.nimbus.host:localhost} 

---

###############################################################################
# Profile - "production"
###############################################################################

# Profile
spring.profiles: production

# Storm
storm:
   local: false
   debug: false

---

###############################################################################
# Profile - "development"
###############################################################################

# Profile
spring.profiles: development

# Storm
storm:
   local: true
   debug: true
