---
# Copyright (c) 2014 fStream. All Rights Reserved.

fstream_user: fstream
fstream_group: fstream
fstream_uid: 3080
fstream_gid: 3080
fstream_rates_password:

influxdb_host: localhost
influxdb_port: 8086

zookeeper_connect: localhost:2181

kafka_broker_list: localhost:9092

storm_host: localhost
storm_port: 6627
