---
# Copyright (c) 2014 fStream. All Rights Reserved.

- name: Make sure the {{ fstream_module }} log dir exists
  file: path=/var/log/{{ fstream_module }} state=directory owner={{ fstream_user }} group={{ fstream_group }} mode=0755 recurse=yes

- name: Copy {{ fstream_module }}
  copy: src={{ fstream_dist_dir }}
        dest={{ staging_dir }}/{{ fstream_archive }}
  
- name: Extract {{ fstream_module }}
  command: "tar zxf /tmp/{{ fstream_archive }} -C /usr/local"
  
- name: Symlink {{ fstream_artifact }}
  file: path=/usr/local/{{ fstream_module }} src=/usr/local/{{ fstream_artifact }} state=link force=yes