---
# Copyright (c) 2014 fStream. All Rights Reserved.

- name: Make sure the storm group is present
  action: group gid={{ fstream_gid }} name={{ fstream_group }} state=present

- name: Make sure the fstream user directory is present
  action: file path="/home/{{ fstream_user }}" state=directory

- name: Make sure the fstream user is present
  user: uid={{ fstream_uid }} name={{ fstream_user }} group={{ fstream_group }} home="/home/{{ fstream_user }}" shell=/bin/bash state=present comment="fstream user"

- name: Set the right fstream user directory permissions
  action: file path="/home/{{ fstream_user }}" owner={{ fstream_user }} group={{ fstream_group }} mode=0700 state=directory

- name: Set the right expiration on the fstream user
  command: "sudo chage -I -1 -E -1 -m -1 -M -1 -W -1 -E -1 {{ fstream_user }}"
