---
# Copyright (c) 2014 fStream. All Rights Reserved.

- name: Install the supervisord storm-nimbus script
  template: src=storm-nimbus.conf.j2 dest=/etc/supervisor.d/storm-nimbus.conf owner=root group=root mode=0644
  notify:
    - Restart storm-nimbus supervisor

- name: Install the supervisord storm-ui script
  template: src=storm-ui.conf.j2 dest=/etc/supervisor.d/storm-ui.conf owner=root group=root mode=0644
  notify:
    - Restart storm-ui supervisor
