- hosts: '{{ server | default("hadoop_client") }}'
  vars:
    zeppelin_git_url: 'https://github.com/apache/incubator-zeppelin.git'
    zeppelin_src_dir: '/usr/src/zeppelin'
    zeppelin_version: 'master'
    zeppelin_comiple_flag: '-Pspark-1.2 -Phadoop-2.4 -Pyarn -DskipTests -P build-distr'
    zeppelin_hadoop_version: '2.5.0-cdh5.3.2'
  roles:
    - jdk
    - maven
  tasks:
    - name: mkdir_zeppelin_dir
      file: path={{ zeppelin_src_dir }}state=directory recurse=yes
    - name: clone_zeppelin_src
      git: repo={{ zeppelin_git_url }} dest={{ zeppelin_src_dir }}/{{ zeppelin_version }}
    - name: create_alternatives_link
      alternatives: name=zeppelin_src path={{ zeppelin_src_dir }}/{{ zeppelin_version }} link={{ zeppelin_src_dir }}/default
    - name: compile_zeppelin
      shell: mvn clean package -Dhadoop.version={{ zeppelin_hadoop_version }} {{ zeppelin_comiple_flag }} chdir={{ zeppelin_src_dir }}/default
    
