---
- name: install the 'Development tools' package group
  yum: name="@Development tools" state=present

- name: install EPEL repository
  yum: name=http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm state=present 

- name: install RPMforge repository
  yum: name=http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm state=present

- name: install some tools for convenience
  yum: name={{ item }} state=present
  with_items:
    - vim
    - tmux
    - htop
    - git
    - python-pycurl
    - libgfortran
    - python-pip
    - nmon
    - sockperf
    - ifotop
    - iotop
    # not available in CentOS
    # - python-swiftclient # can be installed from pip
  tags:
    - install

- name: populate /etc/hosts
  template: src=etc/hosts.j2 dest=/etc/hosts
  tags:
    - configure

