---
# Copyright (c) 2014 fStream. All Rights Reserved.

- name: Check for ip address in config file
  command: grep -E '^\s*hostname.*{{ ansible_default_ipv4.address }}' /opt/influxdb/shared/config.toml
  register: config_has_ip
  ignore_errors: true
  changed_when: false

- name: Delete raft dir before hostname change
  file: dest=/opt/influxdb/shared/data/raft state=absent
  when: config_has_ip|failed

- name: Add current dir
  file: path=/opt/influxdb/current state=directory mode=0755

- name: Update config
  template: src=config.toml dest=/opt/influxdb/current/config.toml
  notify:
    - Restart influxdb
    - Wait for influxdb port
