---
# Copyright (c) 2015 fStream. All Rights Reserved.

# Idempotent way to build a /etc/hosts file with Ansible using your Ansible hosts inventory for a source.
# Will include all hosts the playbook is run on.
# https://gist.github.com/rothgar/8793800 

- name: Build hosts file
  lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item][default_ipv4_interface].ipv4.address }} {{ item }}" state=present
  when: hostvars[item][default_ipv4_interface] is defined
  with_items: "{{ groups['all'] }}"
