---
# Copyright (c) 2015 fStream. All Rights Reserved.

- name: Update hostname
  become: yes
  command: "hostname {{ hostname }}"

- name: Update /etc/hostname
  template: src=hostname.j2 dest=/etc/hostname owner=root group=root mode=064

- name: Update /etc/hosts
  lineinfile: dest=/etc/hosts regexp="^127.0.0.1    {{ fqdn }}    {{ hostname }}" line="127.0.0.1    {{ fqdn }}    {{ hostname }}" state=present

- include: hosts.yml
