---
# Copyright (c) 2015 fStream. All Rights Reserved.

- name: Set JAVA_HOME system wide
  lineinfile: "dest=/etc/environment state=present regexp=^JAVA_HOME line=JAVA_HOME={{ jdk_home }}"

- name: Add the JAVA_HOME to the system environment (/etc/profile)
  lineinfile:
    dest: /etc/profile
    regexp: ^export JAVA_HOME
    line: export JAVA_HOME={{ jdk_home }}

- name: Add the JDK binaries to the system path (/etc/profile)
  lineinfile:
    dest: /etc/profile
    regexp: ^export PATH=\$JAVA_HOME
    line: export PATH=$JAVA_HOME/bin:$PATH    

- name: Inform the system where JDK is located
  command: "update-alternatives --install /usr/bin/{{ item }} {{ item }} {{ jdk_home }}/bin/{{ item }} 1"
  with_items: "{{ jdk_tools }}"

- name: Inform the system that JDK must be the default
  command: "update-alternatives --set {{ item }} {{ jdk_home }}/bin/{{ item }}"
  with_items: "{{ jdk_tools }}"
