---
# Copyright (c) 2015 fStream. All Rights Reserved.

- name: Add the JDK binaries to the system path (/etc/profile)
  lineinfile:
    dest: /etc/profile
    regexp: ^export JAVA_HOME
    line: export JAVA_HOME='{{ jdk_dir }}/jdk'

- name: Add the JDK binaries to the system path (/etc/profile)
  lineinfile:
    dest: /etc/profile
    regexp: ^export PATH=\$JAVA_HOME
    line: export PATH=$JAVA_HOME/bin:$PATH

- name: Inform the system where JDK is located
  command: "update-alternatives --install /usr/bin/{{ item }} {{ item }} {{ jdk_dir }}/jdk/bin/{{ item }} 1"
  with_items: jdk_tools

- name: Inform the system that JDK must be the default
  command: "update-alternatives --set {{ item }} {{ jdk_dir }}/jdk/bin/{{ item }}"
  with_items: jdk_tools
