---
# Copyright (c) 2015 fStream. All Rights Reserved.

- name: Add the JDK binaries to the system path (/etc/profile)
  lineinfile: "dest={{ item.dest }} line={{ item.line }} state={{ item.state }}"
  with_items:
    - { dest: '/etc/profile', regexp: '^JAVA_HOME={{ jdk_dir }}/jdk', line: 'JAVA_HOME={{ jdk_dir }}/jdk', state: 'present' }
    - { dest: '/etc/profile', regexp: '^PATH=.*JAVA_HOME.*', line: 'PATH=$PATH:$HOME/bin:$JAVA_HOME/bin', state: 'present' }

- name: Inform the system where JDK is located
  command: "update-alternatives --install /usr/bin/{{ item }} {{ item }} {{ jdk_dir }}/jdk/bin/{{ item }} 1"
  with_items: jdk_tools

- name: Inform the system that JDK must be the default
  command: "update-alternatives --set {{ item }} {{ jdk_dir }}/jdk/bin/{{ item }}"
  with_items: jdk_tools
