---
# Copyright (c) 2014 fStream. All Rights Reserved.

- name: Update configuration
  template: src=zoo.cfg.j2 dest=/usr/local/zookeeper/conf/zoo.cfg owner={{ zookeeper_user }} group={{ zookeeper_group }} mode=0644

- name: Update myid identifier
  template: src=myid.j2 dest={{ zookeeper_data_dir }}/myid owner={{ zookeeper_user }} group={{ zookeeper_group }} mode=0644
