---
# Copyright (c) 2014 fStream. All Rights Reserved.

- name: Install the supervisord zookeeper script
  template: src=zookeeper.conf.j2 dest=/etc/supervisor.d/zookeeper.conf owner=root group=root mode=0644
  notify:
    - Restart zookeeper supervisor
