---
# Copyright (c) 2014 fStream. All Rights Reserved.

- name: Install the supervisord kibana script
  template: src=kibana.conf.j2 dest=/etc/supervisor.d/kibana.conf owner=root group=root mode=0644
  notify:
    - Restart kibana supervisor
