---
# Copyright (c) 2014 fStream. All Rights Reserved.

- name: Download Kafka distribution
  get_url: "url={{ kafka_archive_url }} dest={{ staging_dir }}/{{ kafka_archive }} mode=0444"
  
# Ensure target dir exists
- name: Creating target dir
  file: "dest={{ target_dir }} state=directory"

# Install the Kakfa files to the specified location
- name: Extract Kafka
  command: "tar xzf {{ staging_dir }}/{{  kafka_archive }} -C {{ target_dir }} creates={{ target_dir }}/{{ kafka_dir }}" 
  