---
# Copyright (c) 2014 fStream. All Rights Reserved.

- name: Make sure the storm dependencies are installed
  apt: pkg={{ item }}
  with_items:
    - unzip
    - libboost-all-dev
    - libboost-dev
    - pkg-config
