---
# Copyright (c) 2014 fStream. All Rights Reserved.

- name: Make sure the storm log dir exists
  file: path={{ storm_log_dir }} state=directory owner={{ storm_user }} group={{ storm_group }} mode=0755 recurse=yes

- name: Download storm distribution
  get_url: "url={{ storm_archive_url }} dest=/tmp/{{ storm_archive }} mode=0444"
  
- name: Creating target dir
  file: "dest=/usr/local/storm-{{ storm_version }} state=directory"

- name: Extract storm
  command: "tar xzf /tmp/{{ storm_archive }} -C /usr/local creates=/usr/local/apache-storm-{{ storm_version }}" 
  
- name: Update the storm install permissions
  file: path=/usr/local/apache-storm-{{ storm_version }} owner={{ storm_user }} group={{ storm_group }} state=directory recurse=yes

- name: Update the symbolic link to the storm install
  file: path=/usr/local/storm src=/usr/local/apache-storm-{{ storm_version }} state=link force=yes

- name: Make sure the local working directory for storm is present
  file: path={{ storm_local_dir }} owner={{ storm_user }} group={{ storm_group }} mode=0750 state=directory
