---
# Copyright (c) 2014 fStream. All Rights Reserved.

- name: Download the jzmq source from the git repo
  git: repo=https://github.com/zeromq/jzmq.git dest=/tmp/jzmq version=90f7dc5fc4586e8fa1f60b9c1615236976787e5e

#- name: prepare the jzmq source
#  shell: ./autogen.sh chdir=/tmp/jzmq
#  shell: ./configure chdir=/tmp/jzmq
#  shell: sudo make -j $machine_cpu_count chdir=/tmp/jzmq

- name: Patch jzmq install for ubuntu - pt. 1
  shell: touch classdist_noinst.stamp chdir=/tmp/jzmq/src

- name: Prepare the jzmq source
  shell: ./autogen.sh chdir=/tmp/jzmq

- name: Configure and make the jzmq source
  shell: cd /tmp/jzmq && export JAVA_HOME=/usr/local/java/jdk && ./configure && make -k -j $machine_cpu_count

- name: Make install jzmq
  shell: cd /tmp/jzmq && sudo make -k install
