---
# Copyright (c) 2014 fStream. All Rights Reserved.

- name: Make sure the storm group is present
  action: group gid={{ storm_gid }} name={{ storm_group }} state=present

- name: Make sure the storm user directory is present
  action: file path="/home/{{ storm_user }}" state=directory

- name: Make sure the storm user is present
  user: uid={{ storm_uid }} name={{ storm_user }} group={{ storm_group }} home="/home/{{ storm_user }}" shell=/bin/bash state=present comment="Storm user"

- name: Set the right storm user directory permissions
  action: file path="/home/{{ storm_user }}" owner={{ storm_user }} group={{ storm_group }} mode=0700 state=directory

- name: Set the right expiration on the storm user
  command: "sudo chage -I -1 -E -1 -m -1 -M -1 -W -1 -E -1 {{ storm_user }}"
