---
# Copyright (c) 2014 fStream. All Rights Reserved.
#
# Description:
#   Global variables for all hosts in all playbooks

# Directories
staging_dir: "/tmp"
fstream_dir: "../../.."

# Versions
fstream_version: "0.0.1-SNAPSHOT"

# Hosts
zookeeper_servers: "{{ hostvars | group_ips(groups, 'zookeeper') }}"  
