---
# Copyright (c) 2014 fStream. All Rights Reserved.

- name: Install the supervisord storm-supervisor script
  template: src=storm-supervisor.conf.j2 dest=/etc/supervisor.d/storm-supervisor.conf owner=root group=root mode=0644
  notify:
    - Restart storm-supervisor supervisor
