---
# Copyright (c) 2014 fStream. All Rights Reserved.
# 
# Project and contact information: https://bitbucket.org/fstream/fstream
# 
# Unauthorized copying of this file, via any medium is strictly prohibited.
# Proprietary and confidential.

###############################################################################
# Profile Activation
###############################################################################

# Available simulation profiles:
# - book
# - fx
# - alerts
# - metrics

# Available input profiles:
# - replay

# Available output profiles:
# - console
# - log
# - file
# - kafka

# Available config profiles:
# - simple
# - fast
# - throughput
# - demo

# Profiles
spring.profiles.active: akka,file

###############################################################################
# Profile - common
###############################################################################

# Remote shell
#   Use ssh -p 2000 fstream@localhost to connect
shell:
  auth.simple.user:
    name: fstream
    password: fstream
    
# Simulation
simulate:
   # Camel
   kafka:
      uri:
        "kafka:\
        ${kafka.producerProperties.metadata.broker.list}?\
        zookeeperConnect=${zk.connect}&\
        partitioner=${kafka.producerProperties.partitioner.class}&\
        serializerClass=${kafka.producerProperties.serializer.class}"
   file:
      # Where to read and write from
      dir: build
      # Playback speed factor. 1.0 = realtime, 10.0 = ten times faster, etc.
      speed: 1.0
   
   # How often to create book snapshot events
   snapshotInterval: 5
   
   # Enable assertions
   validate: false
   
   # Run all actors in a single thread
   singleThreaded: false

   # Active instruments
   instruments:
      - RY
      - BMO
      - TD
      - BBM
      - HUF
      
   # Active brokers
   brokers:
      - TD Ameritrade
      - Fidelity
      - ETrade
      - Scottrade
      - Merrill Edge

   # Agents - Common
   tickDuration: 10ms
   msgResponseTimeout: 5 # in seconds
   tickSize: 0.10
   nonPremiumQuoteDelay: 1000 # in milliseconds
   # all securities trade in same range currently
   minPrice: 8
   maxPrice: 14
   # risk quote delta. Currently fixed at 5 ticks.
   riskDistance: 10
   
   # Agents - Types
   institutional:
      probBuy: 0.49
      probMarket: 0.50
      probBestPrice: 0.80
      probCancel: 0.50 # probabilty of existing order canceled and replaced with new one
      maxTradeSize: 5000
      minSleep: 500 # in millis
      maxSleep: 2000 # in millis
      numAgents: 3000 #3000
      quoteSubscriptionLevel: SUBSCRIBE_QUOTES
   retail:
      probBuy: 0.49
      probMarket: 0.69
      probBestPrice: 0.50
      probCancel: 0.25 # probabilty of existing order canceled and replaced with new one
      maxTradeSize: 1000
      maxSleep: 10000 # in millis
      minSleep: 5000 # in millis
      numAgents: 1500 #1500
      quoteSubscriptionLevel: SUBSCRIBE_QUOTES
   hft:
      probBuy: 0.49
      probMarket: 0.25
      probBestPrice: 0.19
      probCancel: 0.75 # probabilty of existing order canceled and replaced with new one
      maxTradeSize: 2500
      maxSleep: 1000 # in millis
      minSleep: 100 # in millis
      numAgents: 500 #500
      quoteSubscriptionLevel: SUBSCRIBE_QUOTES_PREMIUM

---

###############################################################################
# Profile - "fast"
###############################################################################

# Profile
spring.profiles: fast

# Simulation
simulate:
   tickDuration: 1ms
   institutional:
      minSleep: 1
      maxSleep: 2
   retail:
      minSleep: 1
      maxSleep: 2
   hft:
      minSleep: 1   
      maxSleep: 2

---
      
###############################################################################
# Profile - "simple"
###############################################################################

# Profile
spring.profiles: simple
spring.profiles.include: fast

# Simulation
simulate:
   institutional:
      numAgents: 1
   retail:
      numAgents: 1
   hft:
      numAgents: 1

---

###############################################################################
# Profile - "throughput"
###############################################################################

# Profile
spring.profiles: throughput
spring.profiles.include: fast

# Simulation
simulate:
   institutional:
      numAgents: 50
   retail:
      numAgents: 50
   hft:
      numAgents: 50
      
---

###############################################################################
# Profile - "demo"
###############################################################################

# Profile
spring.profiles: demo

# Simulation
simulate:
   tickDuration: 1s
   institutional:
      numAgents: 5
   retail:
      numAgents: 5
   hft:
      numAgents: 5
