---
# Copyright (c) 2014 fStream. All Rights Reserved.
# 
# Project and contact information: https://bitbucket.org/fstream/fstream
# 
# Unauthorized copying of this file, via any medium is strictly prohibited.
# Proprietary and confidential.

# Spring
spring:
   profiles:
      active: kafka

# Application
simulate:
   seconds: 60
   instruments:
      - RY
      - BMO
      - TD
      - BBM
      - HUF
   msgResponseTimeout: 1 # in seconds
   instProp:
      probBuy: 0.49
      probMarket: 0.30
      probBestPrice: 0.70
      maxTradeSize: 5000
      maxSleep: 2500 # in millis
      minSleep: 1000 # in millis
      numagents: 3000
   retProp:
      probBuy: 0.49
      probMarket: 0.69
      probBestPrice: 0.19
      maxTradeSize: 1000
      maxSleep: 10000 # in millis
      minSleep: 5000 # in millis
      numAgents: 1500
   hftProp:
      probBuy: 0.49
      probMarket: 0.69
      probBestPrice: 0.19
      maxTradeSize: 1000
      maxSleep: 1000 # in millis
      minSleep: 100 # in millis
      numAgents: 500


      
# Kafka
kafka:
   producerProperties:
      metadata.broker.list: ${kafka.broker.list:localhost:6667}
      partitioner.class: kafka.producer.DefaultPartitioner
      serializer.class: kafka.serializer.StringEncoder
      