---
# Copyright (c) 2014 fStream. All Rights Reserved.
# 
# Project and contact information: https://bitbucket.org/fstream/fstream
# 
# Unauthorized copying of this file, via any medium is strictly prohibited.
# Proprietary and confidential.

###############################################################################
# Activation
###############################################################################

# Available simulation profiles:
# - toq
# - rates

# Available output profiles:
# - console
# - log
# - file
# - kafka

# Profiles
spring.profiles.active: toq,file 

###############################################################################
# Profile - Common
###############################################################################

# Simulationguava
simulate:
   kafka:
      uri:
        "kafka:\
        ${kafka.producerProperties.metadata.broker.list}?\
        zookeeperConnect=${zk.connect}&\
        partitioner=${kafka.producerProperties.partitioner.class}&\
        serializerClass=${kafka.producerProperties.serializer.class}"      
   toq:
      uri: ${simulate.kafka.uri}&topic=toq
   rates:
      uri: ${simulate.kafka.uri}&topic=rates
   instruments:
      - RY
      - BMO
      - TD
      - BBM
      - HUF
   brokers:
      - xxx
      - yyy
      - zzz
      - ddd
      - aaa
   msgResponseTimeout: 5 # in seconds
   minTickSize: 0.1
   nonPremiumQuoteDelay: 1000 # in milliseconds
   institutional:
      probBuy: 0.49
      probMarket: 0.30
      probBestPrice: 0.70
      maxTradeSize: 5000
      maxSleep: 2500 # in millis
      minSleep: 1000 # in millis
      numAgents: 3000 #3000
      quoteSubscriptionLevel: SUBSCRIBE_QUOTES
   retail:
      probBuy: 0.49
      probMarket: 0.69
      probBestPrice: 0.19
      maxTradeSize: 1000
      maxSleep: 10000 # in millis
      minSleep: 5000 # in millis
      numAgents: 1500 #1500
      quoteSubscriptionLevel: SUBSCRIBE_QUOTES
   hft:
      probBuy: 0.49
      probMarket: 0.69
      probBestPrice: 0.19
      maxTradeSize: 1000
      maxSleep: 1000 # in millis
      minSleep: 100 # in millis
      numAgents: 500 #500
      quoteSubscriptionLevel: SUBSCRIBE_QUOTES_PREMIUM
