---
# Copyright (c) 2014 fStream. All Rights Reserved.

- name: Make sure the zeromq dependencies are installed
  apt: pkg=binutils-doc

- name: Download the zeromq source in /tmp if not yet present
  command: wget http://download.zeromq.org/zeromq-{{ zeromq_version }}.tar.gz chdir=/tmp creates=/tmp/zeromq-{{ zeromq_version }}.tar.gz

- name: Untar the zeromq source in /tmp
  command: tar -xvzf /tmp/zeromq-{{ zeromq_version }}.tar.gz chdir=/tmp creates=/tmp/zeromq-{{ zeromq_version }}

- name: Configure and make the zeromq source
  shell: cd /tmp/zeromq-{{ zeromq_version }} && ./configure && make -j $machine_cpu_count creates=/tmp/zeromq-{{ zeromq_version }}/Makefile

- name: Make install zeromq
  shell: cd /tmp/zeromq-{{ zeromq_version }} && sudo make install creates=/usr/local/lib/libzmq.so
