# file: roles/zookeeper/meta/main.yml

dependencies:
  - { role: fstream_common, fstream_module: 'fstream-rates', main_class: 'org.springframework.boot.loader.JarLauncher', http_port: '8082', priority: '10' }
