---
# Copyright (c) 2014 fStream. All Rights Reserved.

- name: Update configuration
  template: src=server.properties.j2 dest=/usr/local/kafka/config/server.properties owner={{ kafka_user }} group={{ kafka_group }} mode=0644
  
- name: Update logging
  template: src=log4j.properties.j2 dest=/usr/local/kafka/config/log4j.properties owner={{ kafka_user }} group={{ kafka_group }} mode=0644
  