---
# Copyright (c) 2014 fStream. All Rights Reserved.

- name: Make sure the kafka dependencies are installed
  apt: pkg={{ item }}
  with_items:
    - git
    - libboost-all-dev
    - libboost-dev
    - pkg-config
