---
# Copyright (c) 2014 fStream. All Rights Reserved.

- name: Download Kafka distribution
  get_url: "url={{ kafka_archive_url }} dest={{ staging_dir }}/{{ kafka_archive}} mode=0444 force=no"
  
# Ensure target dir exists
- name: Creating target dir
  file: "dest={{ target_dir }} state=directory"

# Install the Kakfa files to the specified location
- name: Extract Kafka
  command: "tar xzf {{ staging_dir }}/{{  kafka_archive }} -C /usr/local/etc/ creates=/usr/local/etc/{{ kafka_dir }}" 
  
- name: Kafka | Update the kafka install permissions
  file: path=/usr/local/etc/kafka_2.10-0.8.1.1 owner={{ kafka_user }} group={{ kafka_group }} state=directory recurse=yes

- name: Kafka | Update the symbolic link to the kafka install
  file: path=/usr/local/etc/kafka src=/usr/local/etc/kafka_2.10-0.8.1.1 state=link force=yes

- name: Kafka | Make sure the local working directory for kafka is present
  file: path={{ kafka_local_dir }} owner={{ kafka_user }} group={{ kafka_group }} mode=0750 state=directory
