---
# Copyright (c) 2015 fStream. All Rights Reserved.

- name: Add repository
  apt_repository: repo="{{ logstash_apt_repo }}" state=present

- name: Add repo key
  apt_key: url="{{ logstash_repo_key }}" state=present

- name: Install package
  apt: pkg=logstash update_cache=yes state=latest

- name: Configure default settings for Logstash
  template: src=defaults.conf.j2
            dest={{ logstash_defaults_file }}
            owner=root
            group=root
            mode=0644
            backup=yes
  notify:
   - Restart logstash
