---
# Copyright (c) 2015 fStream. All Rights Reserved.

- name: Install python utils
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600 state=latest
  with_items:
  - "python-pycurl"
  - "python-apt"  
