---
# Copyright (c) 2014 fStream. All Rights Reserved.

- name: Enable supervisor
  service: name=supervisor enabled=yes
  become: yes

- name: Start supervisor
  service: name=supervisor state=started
  become: yes

- name: Stop supervisor
  service: name=supervisor state=stopped
  become: yes
  
- name: Restart supervisor
  service: name=supervisor state=restarted
  become: yes
