---
# Copyright (c) 2014 fStream. All Rights Reserved.
#
# fStream - Master playbook 
#
# Description: 
#   The is the base Ansible playbook file for provisioning the fStream system.
#
# See:
#   - http://www.ansibleworks.com/docs/playbooks.html

# This playbook will provision HDFS

# HDFS - Namenode
- hosts: hdfs-namenode
  sudo: yes
  roles:
    - { role: hdfs, hdfs_namenode: True }

# HDFS - Datanode    
- hosts: hdfs-datanode
  sudo: yes
  roles:
    - { role: hdfs, hdfs_namenode: False }
