---
# Copyright (c) 2014 fStream. All Rights Reserved.
#
# fStream - Master playbook 
#
# Description: 
#   The is the master Ansible playbook file for provisioning the fStream system.
#
# See:
#   - http://www.ansibleworks.com/docs/playbooks.html

# ***
# *** Enable this for debugging:
# ***

#- hosts: all
#  tasks:
#    - debug: var=hostvars['influxdb']
#    - debug: var=default_ipv4_interface
#    - debug: var=hostvars['influxdb'][default_ipv4_interface]
#  roles:
#    - { role: hostname, sudo: yes }
#

# Upfront, gather all the IPs required to generate the /etc/hosts on each machine. 
# The alternative would only have cumulative IPs as provisioning proceeds serially through hosts. 
- hosts: all
  gather_facts: True

# Provision the infrastructure
- include: influxdb.yml 
- include: zookeeper.yml
- include: kafka.yml
- include: storm.yml

# Provision the application
- include: fstream-rates.yml
- include: fstream-compute.yml
- include: fstream-persist.yml
- include: fstream-web.yml