---
# Copyright (c) 2014 fStream. All Rights Reserved.
#
# fStream - Master playbook 
#
# Description: 
#   The is the master Ansible playbook file for provisioning the fStream system.
#
# See:
#   - http://www.ansibleworks.com/docs/playbooks.html

# Provision the base setup
- include: playbook-base.yml

# Provision operations
- include: playbook-ops.yml

# Provision the infrastructure
- include: playbook-influxdb.yml 
- include: playbook-zookeeper.yml
- include: playbook-kafka.yml
- include: playbook-storm.yml

# Provision the application
- include: playbook-fstream-rates.yml
- include: playbook-fstream-compute.yml
- include: playbook-fstream-persist.yml
- include: playbook-fstream-web.yml