# -*- mode: ruby -*-
# vi: set ft=ruby :
# Copyright (c) 2014 fStream. All Rights Reserved.
#
# fStream - VirtualBox VM Vagrant file
#
# Description: 
#   The is the Vagrant file for provisioning the fStream stack using the 
#   VirtualBox provider and Ansible as the provisioner.
#
# See:
#   - http://www.ansibleworks.com/docs/
#   - http://www.ansibleworks.com/docs/guide_vagrant.html
#   - http://jinja.pocoo.org/docs/templates/
#   - http://docs.vagrantup.com/v2/provisioning/ansible.html
#   - http://docs.vagrantup.com/v2/virtualbox/configuration.html
#   - https://github.com/pjan/the-ansibles

# vagrant plugin install vagrant-aws

# See https://github.com/mitchellh/vagrant/issues/2924
ENV['VAGRANT_DEFAULT_PROVIDER'] = "aws"
ENV['PYTHONIOENCODING'] = "utf-8"
ENV['ANSIBLE_ROLES_PATH'] = "../../ansible/roles"

# All boxes in the stack
boxes = [{
    :name => "zookeeper",
    :ip => '10.211.55.100',
    :cpu => "50",
    :ram => "512",
    :fowarded_ports => [],
    :aws_instance_type => 't2.micro'
  }, {
    :name => "kafka",
    :ip => '10.211.55.101',
    :cpu => "50",
    :ram => "512",
    :fowarded_ports => [],
    :aws_instance_type => 't2.small'
  }, {
    :name => "storm",
    :ip => '10.211.55.102',
    :cpu => "50",
    :ram => "1024",
    :fowarded_ports => [{
      :guest => 8081, :host=> 8080
    }],
    :aws_instance_type => 't2.small'
  }, {
    :name => "fstream-rates",
    :ip => '10.211.55.103',
    :cpu => "50",
    :ram => "512",
    :fowarded_ports => [],
    :aws_instance_type => 't2.micro'
  }, {
    :name => "fstream-compute",
    :ip => '10.211.55.104',
    :cpu => "50",
    :ram => "512",
    :fowarded_ports => [],
    :aws_instance_type => 't2.micro'
  }, {
    :name => "fstream-web",
    :ip => '10.211.55.105',
    :cpu => "50",
    :ram => "512",
    :fowarded_ports => [{
      :guest => 8080, :host=> 8081 
    }],
    :aws_instance_type => 't2.micro'
}]

Vagrant.configure("2") do |config|
  # Base box
  config.vm.box = "dummy" 
  config.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"

  boxes.each_with_index do |box, index|
    config.vm.define box[:name] do |vms|
      # Hostname of the box 
      vms.vm.hostname = box[:box]
      
		 # Execute AWS provider
		 vms.vm.provider :aws do |aws, override|
		   # Credentials
		   aws.access_key_id = ENV['AMAZON_ACCESS_KEY_ID']
		   aws.secret_access_key = ENV['AMAZON_SECRET_ACCESS_KEY']
		   
		   # Ubuntu AMI
	     aws.ami = "ami-9eaa1cf6"
	     aws.instance_type = box[:aws_instance_type]
		   aws.keypair_name = "fstream-aws-bob"
		   aws.security_groups = ["default"]
		   
		   aws.tags = {
		     "Name" => box[:box]
		   }
		
		   override.vm.box = "dummy"
		   override.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
		   
		   override.ssh.username = "ubuntu"
		   override.ssh.private_key_path = "~/.ssh/fstream-aws-bob.pem"
		 end
        
      if index == boxes.length - 1
	     # Execute Ansible provisioner
	     vms.vm.provision :ansible do |ansible|
          ansible.playbook = "../virtualbox-single/site.yml"
          ansible.groups = {
            "zookeeper"       => ["zookeeper"],
            "kafka"           => ["kafka"],
            "storm"           => ["storm"],
            "fstream-rates"   => ["fstream-rates"],
            "fstream-compute" => ["fstream-compute"],
            "fstream-web"     => ["fstream-web"]
          }
          ansible.limit = 'all'
          ansible.verbose = 'vv'
          
          # Avoids ssh: connect to host <ip-address> port 22: Host is down
          ansible.raw_arguments = "--timeout=60"
	     end 
      end  
    end  
  end
end
